#Requires -Version 5.1
<#
.SYNOPSIS
  Generate packaging/inno/associations.issinc from packaging/wix/file-associations.json
#>
[CmdletBinding()]
param(
    [string]$JsonPath = "",
    [string]$OutPath = ""
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
if (-not $JsonPath) {
    $JsonPath = Join-Path $Root "packaging\wix\file-associations.json"
}
if (-not $OutPath) {
    $OutPath = Join-Path $Root "packaging\inno\associations.issinc"
}

if (-not (Test-Path $JsonPath)) {
    throw "Missing associations JSON: $JsonPath"
}

$data = Get-Content -Raw -Encoding UTF8 $JsonPath | ConvertFrom-Json
$exts = @($data.extensions)
if ($exts.Count -eq 0) {
    throw "No extensions in $JsonPath"
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("; AUTO-GENERATED by scripts/generate_inno_associations.ps1 - do not edit by hand")
$lines.Add("; Source: packaging/wix/file-associations.json")
$lines.Add("")

# OpenWithProgids (always safe - shows under Open with)
foreach ($ext in $exts) {
    $e = $ext.Trim()
    if (-not $e.StartsWith(".")) { $e = ".$e" }
    $lines.Add(('Root: HKCR; Subkey: "{0}\OpenWithProgids"; ValueType: string; ValueName: "MagicEditor.Document"; ValueData: ""; Flags: uninsdeletevalue' -f $e))
}

$lines.Add("")
$lines.Add("; Optional: set MagicEditor as the default handler for each extension")
foreach ($ext in $exts) {
    $e = $ext.Trim()
    if (-not $e.StartsWith(".")) { $e = ".$e" }
    $lines.Add(('Root: HKCR; Subkey: "{0}"; ValueType: string; ValueName: ""; ValueData: "MagicEditor.Document"; Flags: uninsdeletevalue; Tasks: assocdefaults' -f $e))
}

$lines.Add("")
$lines.Add("; Default Programs / Settings - Apps - Default apps capabilities")
foreach ($ext in $exts) {
    $e = $ext.Trim()
    if (-not $e.StartsWith(".")) { $e = ".$e" }
    $lines.Add(('Root: HKLM; Subkey: "Software\MagicEditor\Capabilities\FileAssociations"; ValueType: string; ValueName: "{0}"; ValueData: "MagicEditor.Document"; Flags: uninsdeletevalue' -f $e))
}

$dir = Split-Path -Parent $OutPath
if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}
[System.IO.File]::WriteAllText($OutPath, ($lines -join "`r`n") + "`r`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($exts.Count) extensions -> $OutPath"
